// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearMessages():Promise<void>;

export function Connect(arg1:main.ConnectOptions):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function FormatJSON(arg1:string):Promise<string>;

export function GetMessages(arg1:number,arg2:number):Promise<Array<main.Msg>>;

export function GetPaths():Promise<Record<string, string>>;

export function GetProfiles():Promise<Array<main.Profile>>;

export function GetStatus():Promise<main.Status>;

export function ListSessions():Promise<Array<main.SessionInfo>>;

export function LoadSession(arg1:string):Promise<main.SessionDetail>;

export function OpenLogDir():Promise<void>;

export function PickAndLoadSession():Promise<main.SessionDetail>;

export function RecordHTTP(arg1:main.HTTPExchange):Promise<main.HTTPExchange>;

export function RecordWS(arg1:main.ConnectOptions,arg2:string,arg3:string):Promise<main.WSRecord>;

export function RequestHTTP(arg1:main.ConnectOptions,arg2:string):Promise<main.HTTPExchange>;

export function SaveProfile(arg1:main.Profile):Promise<void>;

export function SearchSessions(arg1:string):Promise<Array<main.SessionInfo>>;

export function SelectProfile(arg1:string):Promise<void>;

export function Send(arg1:string):Promise<void>;
