// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearMessages() {
  return window['go']['main']['App']['ClearMessages']();
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function FormatJSON(arg1) {
  return window['go']['main']['App']['FormatJSON'](arg1);
}

export function GetMessages(arg1, arg2) {
  return window['go']['main']['App']['GetMessages'](arg1, arg2);
}

export function GetPaths() {
  return window['go']['main']['App']['GetPaths']();
}

export function GetProfiles() {
  return window['go']['main']['App']['GetProfiles']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function LoadSession(arg1) {
  return window['go']['main']['App']['LoadSession'](arg1);
}

export function OpenLogDir() {
  return window['go']['main']['App']['OpenLogDir']();
}

export function PickAndLoadSession() {
  return window['go']['main']['App']['PickAndLoadSession']();
}

export function SaveProfile(arg1) {
  return window['go']['main']['App']['SaveProfile'](arg1);
}

export function SearchSessions(arg1) {
  return window['go']['main']['App']['SearchSessions'](arg1);
}

export function Send(arg1) {
  return window['go']['main']['App']['Send'](arg1);
}
